### PR TITLE
Fixes highlights with paragraph breaks

### LINKED ISSUE #123: Bug: highlighting across paragraphs breaks
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour

Highlighting across paragraphs breaks.

### Expected behaviour

Should not break.

### Steps to reproduce

1. Highlight text across 2 or more paragraphs (blocks)
2. Change color
3. Hihglight text across the same 2 paragraphs but a sub section of the text that is highlighted already
4. Observe some text shifting

### Screenshots

screenshot-20210601T110226-5uTMqerN

### Logs 

N/A

### Configuration

- OS: macOS
- Browser: Firefox
- Browser version: 88

### PR DESCRIPTION
**Pull request by sinderpl**
Fixes #123  .

Changes proposed in this pull request:
 - Remove parent checks from nextSibling, it is already checked for null in the outer if statement
 - Replicate the functionality of the NextSibling if statement checks for the PreviousSibling checks.
 -

### CODE REVIEW

**Comment by moltar** [comment]
@sinderpl Awesome! :) Thanks 🎉

**Comment by moltar** [comment]
@lastlink Can this be released, please? We really need this for production.

**Comment by lastlink** [comment]
Just noticed this. I'll try to get this out next week. I'm going to test it first.

**Comment by moltar** [comment]
@lastlink can we merge this, please? We really need this fix in production :)

**Review by lastlink — APPROVED** [review]

**Pull request closed without merging**
